name: Scrape Daily

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  monthly_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run scrape current month script
        run: ./scripts/scrape.sh --current-month
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
